### PR TITLE
Remove unused SEO features.

### LINKED ISSUE #27: phpBB SEO
Hi!

In your [lang file](https://github.com/ErnadoO/ext-phpbb-directory/blob/master/language/en/info_acp_directory.php#L53-L54) you specify that the rewriting is based on the DCZ's Ultimate SEO URL MOD.
For phpBB 3.1 and newer, MODs don't work. :-D
And, since a couple of days, http://www.phpbb-seo.com/ is down and the SEO extension abandonned.

### PR DESCRIPTION
**Pull request by Skouat**
See : https://github.com/ErnadoO/ext-phpbb-directory/issues/27#issuecomment-274334963

Fix #27

### CODE REVIEW

**Comment by Skouat** [comment]
Not sure about the update of `composer.json` and the name of the migration file.
Please let me know. ;)

**Comment by ErnadoO** [comment]
No need to update composer file for 3.2 branch, because this version is stil in dev state.

For migration file, "remove_rewrite_conf" will be fine, depends of 1_0_0

**Comment by Skouat** [comment]
Ooops bad branch. It was for 3.1.x, but if you don't plan to publish new release for 3.1. Indeed, no need to update the composer.json.

**Comment by ErnadoO** [comment]
I changes base branch, no worry :)

Indeed, no new releases for 3.1 ;)

**Comment by Skouat** [comment]
I close this PR, to recreate one based on the 3.2 branch.
It will be better for the Git log history ;)

**Pull request closed without merging**
